DISKETTE_VOLUME = 1.44
NUMBER_OF_PAGES = 100
NUMBER_OF_LINES_PER_PAGE = 50
NUMBER_OF_CHARACTERS_PER_LINE = 25
MEMORY = 4
book = ((DISKETTE_VOLUME * 1024 * 1024) // ((MEMORY) *
      (NUMBER_OF_PAGES * NUMBER_OF_LINES_PER_PAGE * NUMBER_OF_CHARACTERS_PER_LINE)))
print("Количество книг, помещающихся на дискету:",int(book))
